name: Test

on:
  workflow_dispatch:
  push:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Apt
        run: apt install -y socat openjdk-21-jdk-headless openjdk-21-jre-headless

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run
        run: scripts/test.sh
