name: Test

on:
  workflow_dispatch:
  push:

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run
        run: go run . -v -- curl https://www.example.com

